version: '3.5'  # Define a versão do Docker Compose a ser usada

services:
  # Serviço do MySQL para o Zabbix
  zabbix-mysql:
    image: mysql:5.7  # Usa a imagem do MySQL na versão 5.7
    container_name: zabbix-mysql  # Nome do container para fácil referência
    environment:
      MYSQL_ROOT_PASSWORD: zabbix_p@ss753  # Senha do root do MySQL (pode ser alterada)
      MYSQL_DATABASE: zabbix  # Nome do banco de dados a ser criado para o Zabbix (pode ser alterado)
      MYSQL_USER: zabbix  # Usuário MySQL que o Zabbix usará (pode ser alterado)
      MYSQL_PASSWORD: zabbix_sql789!  # Senha para o usuário Zabbix (pode ser alterada)
    networks:
      zabbix_network:  # Conecta o MySQL à rede personalizada
        ipv4_address: 172.30.2.14  # Endereço IP estático atribuído ao MySQL (pode ser alterado)
    volumes:
      - ./mysql_data:/var/lib/mysql  # Persistência dos dados do MySQL no diretório local (pode mudar o caminho local)
    restart: unless-stopped  # Reinicia o container se ele parar, exceto se for manualmente interrompido

  # Serviço do Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0  # Usa a imagem do Zabbix Server com suporte a MySQL
    container_name: zabbix-server  # Nome do container
    environment:
      DB_SERVER_HOST: zabbix-mysql  # Aponta para o host do MySQL (não alterar, a menos que o MySQL mude)
      MYSQL_DATABASE: zabbix  # Banco de dados usado pelo Zabbix (deve corresponder ao MySQL)
      MYSQL_USER: zabbix  # Usuário que se conecta ao MySQL (deve corresponder ao MySQL)
      MYSQL_PASSWORD: zabbix_sql789!  # Senha do MySQL (deve corresponder ao MySQL)
    depends_on:
      - zabbix-mysql  # Certifica-se de que o MySQL esteja rodando antes de iniciar o Zabbix Server
    networks:
      zabbix_network:  # Conecta o Zabbix Server à rede personalizada
        ipv4_address: 172.30.2.15  # Endereço IP estático do Zabbix Server (pode ser alterado)
    ports:
      - "10051:10051"  # Expõe a porta 10051 para o Zabbix Server (pode ser alterado se houver conflito)
    restart: unless-stopped  # Reinicia automaticamente se parar

  # Serviço do Zabbix Web com Nginx
  zabbix-web-nginx:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0  # Interface web do Zabbix com Nginx
    container_name: zabbix-web  # Nome do container
    environment:
      ZBX_SERVER_HOST: zabbix-server  # Aponta para o servidor Zabbix (não alterar)
      DB_SERVER_HOST: zabbix-mysql  # Aponta para o host do MySQL (não alterar)
      MYSQL_DATABASE: zabbix  # Banco de dados usado (deve corresponder ao MySQL)
      MYSQL_USER: zabbix  # Usuário do MySQL (deve corresponder ao MySQL)
      MYSQL_PASSWORD: zabbix_sql789!  # Senha do MySQL (deve corresponder ao MySQL)
    depends_on:
      - zabbix-server  # Certifica-se de que o Zabbix Server esteja rodando antes de iniciar o frontend
      - zabbix-mysql  # Certifica-se de que o MySQL esteja rodando
    networks:
      zabbix_network:  # Conecta o Zabbix Web à rede
        ipv4_address: 172.30.2.17  # Endereço IP estático do Zabbix Web (pode ser alterado)
    ports:
      - "8080:8080"  # Porta para acessar a interface web (pode ser alterada)
    restart: unless-stopped  # Reinicia automaticamente se parar

  # Serviço do Zabbix Agent
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.0  # Agente do Zabbix para coleta de dados
    container_name: zabbix-agent  # Nome do container
    environment:
      ZBX_SERVER_HOST: zabbix-server  # Aponta para o servidor Zabbix
    depends_on:
      - zabbix-server  # Certifica-se de que o Zabbix Server esteja rodando
    networks:
      zabbix_network:  # Conecta o agente à rede
        ipv4_address: 172.30.2.18  # Endereço IP estático do agente (pode ser alterado)
    ports:
      - "10050:10050"  # Porta para o Zabbix Agent (pode ser alterada)
    restart: unless-stopped  # Reinicia automaticamente se parar

  # Serviço do Grafana
  grafana:
    image: grafana/grafana-oss:latest  # Usa a versão mais recente do Grafana Open Source
    container_name: grafana  # Nome do container
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana_pass  # Senha do administrador do Grafana (pode ser alterada)
    depends_on:
      - zabbix-server  # Certifica-se de que o Zabbix Server esteja rodando
    networks:
      zabbix_network:  # Conecta o Grafana à rede
        ipv4_address: 172.30.2.16  # Endereço IP estático do Grafana (pode ser alterado)
    ports:
      - "3000:3000"  # Porta para acessar o Grafana (pode ser alterada)
    volumes:
      - ./grafana_data:/var/lib/grafana  # Persistência de dados do Grafana (pode alterar o diretório local)
    restart: unless-stopped  # Reinicia automaticamente se parar

# Configuração da rede personalizada para os serviços
networks:
  zabbix_network:
    driver: bridge  # Usa o driver de rede "bridge"
    ipam:
      config:
        - subnet: 172.30.0.0/16  # Definindo a sub-rede (pode ser alterada)
